name: "Debug Template"
about: "Used to validate issue forms rendering"
title: "[Debug] "
labels: ["debug"]
body:
  - type: textarea
    attributes:
      label: "Does this show up?"
      description: "If yes, your issue forms work."
    validations:
      required: true
